name: EC2 Deployment

on:
  workflow_run:
    workflows: [ CITests, CICodeCoverage, CILinting, CIStan ]
    types:
      - completed
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy files to the temporary directory
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          overwrite: true
          source: "composer.json,composer.lock,index.php,makefile,manifest.json,bin/,cfg/,css/,i18n/,img/,js/,lib/,tpl/,tst/"
          target: '/tmp/PrivateBin/'

      - name: Move files to the target directory and install dependencies
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo mkdir -p /var/www/html/
            sudo mv /tmp/PrivateBin/* /var/www/html/
            cd /var/www/html/
            sudo composer install --ignore-platform-reqs
      
