name: EC2 Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy files to the deployment server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          overwrite: true
          source: "composer.json,composer.lock,index.php,makefile,manifest.json,bin/,cfg/,css/,i18n/,img/,js/,lib/,tpl/,tst/"
          target: '/var/www/html/PrivateBin/'

      - name: Install dependencies
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script:
            cd /var/www/html ;
            composer install --ignore-platform-reqs
