name: CI

on: [push]

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: php-actions/composer@v6

    - uses: php-actions/phpunit@v3
      with:
          version: 9.6.11
          php_extensions: gd xdebug
      env:
          XDEBUG_MODE: coverage

  code-coverage-summary:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: php-actions/composer@v6
      - uses: php-actions/phpunit@v3
        with:
          version: 9.6.11
          php_extensions: gd xdebug
        env:
          XDEBUG_MODE: coverage

      - name: Debug - Show working directory and files
        run: |
          pwd
          ls -la log

      - name: Code Coverage Summary
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: log/coverage.cobertura.xml

  code-sniffer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: php-actions/composer@v6

      - name: PHP Code Sniffer
        uses: php-actions/phpcs@v1
        with:
          php_version: 8.1
          path: lib/
          standard: phpcs.xml
          ignore: lib/*

  mess-detector:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: php-actions/composer@v6

      - name: PHP Mess Detector
        uses: php-actions/phpmd@v1
        with:
          php_version: 8.1
          path: lib/
          output: text
          ruleset: phpmd.xml
          args: --ignore-violations-on-exit

  stan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: php-actions/composer@v6

      - name: PHPStan
        uses: php-actions/phpstan@v3
        with:
          php_version: 8.1
          path: lib/
          level: 0
          args: --no-progress