name: CICodeCoverage

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: php-actions/composer@v6 # or alternative dependency management
    - uses: php-actions/phpunit@v3
      with:
          version: 9.6.11
          php_extensions: gd, xdebug

    - name: Debug - Show working directory and files
      run: |
        pwd
        ls -la log
      
    - name: Code Coverage Summary
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: log/coverage.cobertura.xml
